{
 "title": "Inference Project Dashboard",
 "time": { "from": "2022-05-13T08:07:22.100Z", "to": "2022-05-13T20:07:22.100Z" },
 "panels": [
  {
   "title": "Number of Seldon Deployment",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(seldon_api_executor_client_requests_seconds_count) by (namespace)"
    }
   ]
  },
  {
   "title": "Request per seconds client side from Seldon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(seldon_api_executor_client_requests_seconds_count[2s])"
    }
   ]
  },
  {
   "title": "Request per seconds server side from Seldon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(seldon_api_executor_server_requests_seconds_count[2s])"
    }
   ]
  },
  {
   "title": "Container CPU Usage from CAdvisor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{ namespace=\"default\"}[1m])"
    }
   ]
  },
  {
   "title": "Container Memory Usage from CAadvisor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"}"
    }
   ]
  },
  {
   "title": "Pod CPU usage CAadvisor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"default\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Request Success rate from istio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(istio_requests_total{destination_workload_namespace=~\"default\",response_code!~\"5.*\",app_kubernetes_io_managed_by=\"seldon-core\"}[5m]) / irate(istio_requests_total{destination_workload_namespace=~\"default\",app_kubernetes_io_managed_by=\"seldon-core\"}[5m])"
    }
   ]
  }
 ]
}