# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chunk_pb2 as chunk__pb2


class FileServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.upload_batch = channel.unary_unary(
        '/FileServer/upload_batch',
        request_serializer=chunk__pb2.BatchChunk.SerializeToString,
        response_deserializer=chunk__pb2.Reply.FromString,
        )


class FileServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def upload_batch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'upload_batch': grpc.unary_unary_rpc_method_handler(
          servicer.upload_batch,
          request_deserializer=chunk__pb2.BatchChunk.FromString,
          response_serializer=chunk__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
